<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPcwMZqM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPcwMZqM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPcwMZqM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPcwMZqM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPcwMZqM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PcwMZqM',
    'container.build_id' => 'ee833e34',
    'container.build_time' => 1582054778,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPcwMZqM');
